config/routes.rb
Statting::Application.routes.draw do
  root 'wallet#index'

  get '/wallet', to: 'wallet#address', as: 'wallet_address'
  get '/address_data/:btc_address', to: 'wallet#address_data'
  get '/about', to: 'wallet#about'
  get '/discuss', to: 'wallet#discuss'

  get '/coinshift/month_performance', to: 'coinshift#month_performance'

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :balances
  has_many :hash_rates
  has_many :payouts

  # [[timestamp, value], [timestamp, value], ...]
  def to_stockchart
    exchanged = balances.map { |b| [b.created_at.to_i*1000, b.exchanged] }
    unexchanged = balances.map { |b| [b.created_at.to_i*1000, b.unexchanged] }
    hashrates = hash_rates.map { |h| [h.created_at.to_i*1000, h.hash_rate] }
    rejectrates = hash_rates.map { |h| [h.created_at.to_i*1000, h.reject_rate] }
    estimated_total = balances.last.exchanged + balances.last.unexchanged

    Hash[
      'last_updated', DateTime.now.utc.to_s(:db),
      'last_exchanged', balances.last.exchanged,
      'last_unexchanged', balances.last.unexchanged,
      'last_hash', hash_rates.last.hash_rate,
      'last_reject', hash_rates.last.reject_rate,
      'estimated_total', estimated_total.round(8),
      'exchanged', exchanged,
      'unexchanged', unexchanged,
      'hashrates', hashrates,
      'rejectrates', rejectrates
    ]
  end
end

app/models/balance.rb
class Balance < ActiveRecord::Base
  belongs_to :address
end

app/models/coinshift.rb
class Coinshift
  require 'open-uri'
  require 'json'

  COINSHIFT_URL = 'http://coinshift.com'
  MONTH_PERFORMANCE_URL = "#{COINSHIFT_URL}/graph/api/v1/performance/30d"
  ADDRESS_URL = 'http://coinshift.com/api/stats/address/:address'

  def self.month_performance
    json = Rails.cache.fetch(['month_performance'], expires_in: 10.minutes) do
      JSON.parse(open(MONTH_PERFORMANCE_URL).read)
    end

    transform_month_performance(json) unless json.empty?
  end

  def self.address_data(address)
    json = Rails.cache.fetch(['address', address], expires_in: 10.minutes) do
      address_url = ADDRESS_URL.gsub(':address', address)
      JSON.parse(open(address_url).read)
    end
  rescue
    {} # Address was not found, so we return an empty hash
  end

  private

  def self.transform_month_performance(json)
    btc_per_mh = reverse_datapoints json[0]['datapoints']
    hashrate = reverse_datapoints json[1]['datapoints']
    reject = reverse_datapoints json[2]['datapoints']

    btc_per_mh = convert_to_javascript_time btc_per_mh
    hashrate = convert_to_javascript_time hashrate
    reject = convert_to_javascript_time reject

    Hash[
      json[0]['target'], btc_per_mh,
      json[1]['target'], hashrate,
      json[2]['target'], reject
    ]
  end

  def self.reverse_datapoints(datapoint)
    datapoint.map { |k, v| [v, k] }
  end

  def self.convert_to_javascript_time(array)
    array.map { |timestamp, value| [timestamp*1000, value] }
  end
end

app/models/hash_rate.rb
class HashRate < ActiveRecord::Base
  belongs_to :address
end

app/models/payout.rb
class Payout < ActiveRecord::Base
  belongs_to :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coinshift_controller.rb
class CoinshiftController < ApplicationController
  def month_performance
    respond_to do |format|
      format.json { render json: Coinshift.month_performance }
    end
  end
end

app/controllers/wallet_controller.rb
class WalletController < ApplicationController
  def address
    btc_address = params[:btc_address]

    if Bitcoin::valid_address?(btc_address)
      @btc_address = Address.find_or_create_by(address: btc_address)
    else
      flash[:warning] = 'Invalid BTC Address'
      redirect_to root_path
    end
  end

  def address_data
    btc_address = Address.find_by address: params[:btc_address]

    json = Rails.cache.fetch(['address_data', btc_address.address], expires_in: 5.minutes) do
      btc_address.to_stockchart
    end

    respond_to do |format|
      format.json { render json: json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coinshift_helper.rb
module CoinshiftHelper
end

app/helpers/wallet_helper.rb
module WalletHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= content_for(:title) || 'Statting' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/menu' %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{name} alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>

  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_coinshift_graphs.html.erb
<%= javascript_include_tag 'coinshift' %>

<div id="coinshift_monthly"></div>
<div id="coinshift_btc"></div>

app/views/shared/_footer.html.erb
<div id="site-footer">
  <small>
    Statting, Copyright <%= Time.now.year %>

    <br>

    <b>If you like this site, please consider donating to <a href="bitcoin:16ENCRHBtSfDSJeE8TVTqcY9L5eXdiHJWg">16ENCRHBtSfDSJeE8TVTqcY9L5eXdiHJWg</a></b>
  </small>
</div>

app/views/shared/_menu.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, :class => "navbar-brand" do %>
        <i>Statting</i>
      <% end %>
    </div>

    <div class="collapse navbar-collapse">

      <form action="<%= wallet_address_path %>" method="GET" class="navbar-form navbar-right">
        <%= content_tag :div, class: 'form-group' do %>
          <%= text_field_tag :btc_address, @btc_address.try(:address), class: 'form-control ', placeholder: 'BTC Address' %>
        <% end %>
        <%= submit_tag 'Search', name: '', class: 'btn btn-primary btn-sm' %>
      </form>

      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Discuss', discuss_path %></li>
      </ul>
    </div>

  </div>
</div>

app/views/wallet/_address_charts_data.html.erb
<script type="text/javascript">
  $(function() {
    var fiveMinutes = 1000*60*5;
    var drawAddressCharts = function() {
      $.getJSON("/address_data/<%= @btc_address.address %>.json", function(data) {

        // Last Updated
        $('#last-updated').text(data.last_updated);
        $('#current-hash').text(data.last_hash);
        $('#current-reject').text(data.last_reject);
        $('#current-exchanged').text(data.last_exchanged);
        $('#current-unexchanged').text(data.last_unexchanged);
        $('#estimated-total').text(data.estimated_total);

        // Draw charts
        $("#hashrate_chart").highcharts("StockChart", {
          chart: {
            zoomType: 'xy'
          },
          rangeSelector: {
            selected: 0,
            buttons: [
              {
                type: 'day',
                count: 1,
                text: '1d'
              }, {
                type: 'day',
                count: 3,
                text: '3d'
              }, {
                type: 'week',
                count: 1,
                text: '1w'
              }
            ]
          },
          title: {
            text: "Hash & Rejects"
          },
          series: [
            {
              name: "Hashrate (KH)",
              data: data.hashrates
            }, {
              name: "Rejected (KH)",
              data: data.rejectrates
            }
          ]
        });

        $("#balance_chart").highcharts("StockChart", {
          chart: {
            zoomType: 'xy'
          },
          rangeSelector: {
            selected: 0,
            buttons: [
              {
                type: 'day',
                count: 1,
                text: '1d'
              }, {
                type: 'day',
                count: 3,
                text: '3d'
              }, {
                type: 'week',
                count: 1,
                text: '1w'
              }
            ]
          },
          title: {
            text: "Balance"
          },
          series: [
            {
              name: "Exchanged (BTC)",
              data: data.exchanged
            }, {
              name: "Unexchanged (BTC)",
              data: data.unexchanged
            }
          ]
        });
      });
    }

    drawAddressCharts();
    setInterval(drawAddressCharts, fiveMinutes);
  });
</script>

app/views/wallet/about.html.erb
<h2>About</h2>

<p>
Stating is a project that aims getting a better user interactivity with CoinShift data.
</p>

<h2>Features</h2>

After inputing your address in the "BTC Address" field Statting will automatically fetch your CoinShift data, and update your charts.

<ul>
  <li>Detailed graphs</li>
  <li>CoinShift stats are updated every 1 hour</li>
  <li>Real time updates every 5 minutes (no need to refresh the browser)</li>
  <li>Background data fetch (no need to keep your browser open)</li>
</ul>

<small>
Statting keep data for a better user visualization of its history and statistics. Please note that this project is not responsible for any data loss.
</small>

<h2>Technologies</h2>

Statting is a Rails application with some background workers. You can check the source code on <a href="http://github.com/tiagoamaro/statting" target="_blank">GitHub</a>

<h2>Work in Progress (Todo list)</h2>

<ul>
  <li>Email notifications</li>
  <li>Average values (hashrate, balance, etc)</li>
</ul>

<h2>Development</h2>

Statting is a weekend project that I work for fun. I don't know how much time I'm going to take to implement new features to it, so please be patient :)

<h2>License</h2>

Statting is under the "MIT" license. For more information check the <a href="http://choosealicense.com/licenses/mit/" target="_blank">license info on choosealicense.com</a>

<h2>Contact</h2>

If you want to share some thoughts about statting, please, use the <%= link_to 'Discuss', discuss_path %> session, <a href="http://www.reddit.com/r/coinshift">CoinShift subReddit</a> or <a href="http://twitter.com/tiagocis">send me a tweet</a>

<br>
<br>

app/views/wallet/address.html.erb
<%= render 'wallet/address_charts_data' %>

<div class="panel panel-default">
  <div class="panel-body">
    <b>Address:</b> <%= @btc_address.address %> <br>
    <hr>
    <b>Current Hash:</b> <span id="current-hash"></span> Kh/s <br>
    <b>Current Reject:</b> <span id="current-reject"></span> Kh/s <br>
    <hr>
    <b>Current Exchanged:</b> <span id="current-exchanged"></span> BTC<br>
    <b>Current Unexchanged:</b> <span id="current-unexchanged"></span> BTC<br>
    <b>Estimated Total:</b> <span id="estimated-total"></span> BTC<br>
    <hr>
    <b>Last Updated:</b> <span id="last-updated"></span>
  </div>
  <div class="panel-footer">
    <li>Charts are updated every 5 minutes. There is no need to reload the page.</li>
  </div>
</div>

<h2>Hashrate</h2>
<div id="hashrate_chart"></div>

<h2>Balance</h2>
<div id="balance_chart"></div>

<h2>Payouts</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Payout Time</th>
      <th>Value</th>
      <th>Tx ID</th>
    </tr>
  </thead>
  <tbody>
    <% @btc_address.payouts.all(order: 'timestamp DESC').each do |payout| %>
      <tr>
        <td><%= payout.timestamp %></td>
        <td><%= payout.value %></td>
        <td>
          <%= link_to payout.tx, "https://blockchain.info/tx/#{payout.tx}", target: '_blank' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/wallet/discuss.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'statting'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/wallet/index.html.erb
<h1>Statting</h1>
<div class="panel panel-default">
  <div class="panel-body">
    Welcome.

    <br>

    Statting is a project that aims to show detailed statistics of the <a href="http://coinshift.com" target="_blank">CoinShift</a> Pool.
  </div>
</div>

<h2>CoinShift Graphs</h2>

<%= render 'shared/coinshift_graphs' %>